name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.AZURE_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.AZURE_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/guestara-assignment:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/guestara-assignment:${{ github.sha }}

    - name: Deploy to Azure Web App
      run: |
        az login --service-principal -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{secrets.TENANT_ID}}
        az webapp config container set --name guestara-assignment --resource-group guestaraResourceG --docker-custom-image-name ${{ secrets.AZURE_CONTAINER_REGISTRY }}/guestara-assignment:${{ github.sha }} --docker-registry-server-url https://${{ secrets.AZURE_CONTAINER_REGISTRY }}
